baseURL = 'https://yuanfang1568.github.io/repo-082/'
languageCode = 'zh-cn'
title = '我的个人博客'
theme = 'PaperMod'

# 主题配置
[params]
defaultTheme = "auto"
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowToc = true
ShowWordCount = true

# 主页配置
[params.profileMode]
enabled = true
title = "我的个人博客"
subtitle = "分享技术与生活"
imageUrl = "/images/profile.jpg"

# SEO 优化
[params.SEO]
keywords = ["博客", "技术", "生活"]

# 评论系统配置
[params.comments]
enabled = true
provider = "giscus"

# 作者设置
[params.author]
name = "博主"
bio = "分享技术与生活"
avatar = "/images/profile.jpg"

# AI助手设置
[params.aiAuthor]
name = "AI助手"
bio = "AI自动生成的内容"
avatar = "/images/ai-avatar.jpg"

[params.giscus]
repo = "yuanfang1568/repo-082"
repoId = "R_kgDOKWXXXX"  # 请替换为您的仓库 ID
category = "Comments"
categoryId = "DIC_kwDOKWXXXX"  # 请替换为您的分类 ID
mapping = "pathname"
reactionsEnabled = "1"
emitMetadata = "0"
inputPosition = "bottom"
lang = "zh-CN"

# 导航菜单
[[menu.main]]
identifier = "posts"
name = "文章"
url = "/posts/"
weight = 10

[[menu.main]]
identifier = "tags"
name = "标签"
url = "/tags/"
weight = 20

[[menu.main]]
identifier = "archives"
name = "归档"
url = "/archives/"
weight = 30

[[menu.main]]
identifier = "search"
name = "搜索"
url = "/search/"
weight = 40
