name: AI Batch Post Generation

on:
  schedule:
    - cron: '0 */12 * * *'  # 每12小时运行一次
  workflow_dispatch:
    inputs:
      post_count:
        description: '要生成的文章数量'
        required: true
        default: '20'
        type: number
  workflow_dispatch:      # 允许手动触发

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  OPENAI_API_ORG: ${{ secrets.OPENAI_API_ORG }}

jobs:
  create-post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai python-frontmatter python-slugify

      - name: Generate post
        run: python .github/scripts/generate_post.py

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add content/posts/
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto generated post $(date +'%Y-%m-%d')" && git push)
